<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Evoogle.ApiFramework</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Humanizer.Core" Version="3.0.10" />
    <PackageReference Include="Evoogle.Core"
                      Version="$(EvoogleCorePackageVersion)"
                      Condition="'$(UseLocalEvoogleProjectReferences)' != 'true'
                                 And '$(EvoogleCorePackageVersion)' != ''" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Evoogle.ApiFramework.Annotations\Evoogle.ApiFramework.Annotations.csproj" />
    <ProjectReference Include="..\..\..\evoogle-core\Source\Evoogle.Core\Evoogle.Core.csproj"
                      Condition="'$(UseLocalEvoogleProjectReferences)' == 'true'" />
  </ItemGroup>

  <Target Name="ValidateEvoogleCorePackageVersion"
          BeforeTargets="Restore;PrepareForBuild"
          Condition="'$(UseLocalEvoogleProjectReferences)' != 'true'
                     And '$(EvoogleCorePackageVersion)' == ''">
    <Error Text="Configure Core package version or enable local project references." />
  </Target>

</Project>
