// Copyright (c) 2024-2025 Evoogle.com
// SPDX-License-Identifier: MIT
//
// This file is licensed under the MIT License.
// See the LICENSE file in the project root for more information.
namespace Evoogle.ApiFramework.Schema;

public enum ApiInitializationCode
{
    #region ApiCollectionType Initialization Codes
    API_COLLECTION_TYPE_NULL_ITEM_TYPE,
    API_COLLECTION_TYPE_UNRESOLVED_ITEM_TYPE,
    #endregion

    #region ApiEnumType Initialization Codes
    API_ENUM_TYPE_DUPLICATE_VALUE_API_NAME,
    API_ENUM_TYPE_DUPLICATE_VALUE_CLR_NAME,
    API_ENUM_TYPE_DUPLICATE_VALUE_CLR_ORDINAL,
    API_ENUM_TYPE_INVALID_CLR_TYPE,
    API_ENUM_TYPE_NULL_OR_EMPTY_VALUES,
    #endregion

    #region ApiEnumValue Initialization Codes
    API_ENUM_VALUE_INVALID_API_NAME,
    API_ENUM_VALUE_INVALID_CLR_NAME,
    #endregion

    #region ApiIdentitySet Initialization Codes
    API_IDENTITY_SET_DUPLICATE_API_NAME,
    API_IDENTITY_SET_INVALID_PRIMARY_API_NAME,
    API_IDENTITY_SET_NULL_OR_EMPTY_IDENTITIES,
    API_IDENTITY_SET_UNRESOLVED_PRIMARY,
    #endregion

    #region ApiIdentity Initialization Codes
    API_IDENTITY_DUPLICATE_PART_API_PROPERTY_NAME,
    API_IDENTITY_INVALID_API_NAME,
    API_IDENTITY_MIXED_ORDERED_AND_NAMED_PARTS,
    API_IDENTITY_NULL_OR_EMPTY_PARTS,
    #endregion

    #region ApiIdentityPart Initialization Codes
    API_IDENTITY_PART_INVALID_API_PROPERTY_NAME,
    API_IDENTITY_PART_UNRESOLVED_PROPERTY,
    #endregion

    #region ApiNamedType Initialization Codes
    API_NAMED_TYPE_INVALID_API_NAME,
    API_NAMED_TYPE_NULL_CLR_TYPE,
    #endregion

    #region ApiObjectType Initialization Codes
    API_OBJECT_TYPE_DUPLICATE_PROPERTY_API_NAME,
    API_OBJECT_TYPE_DUPLICATE_PROPERTY_CLR_NAME,
    API_OBJECT_TYPE_DUPLICATE_RELATIONSHIP_API_NAME,
    API_OBJECT_TYPE_NULL_OR_EMPTY_PROPERTIES,
    #endregion

    #region ApiProperty Initialization Codes
    API_PROPERTY_INVALID_API_NAME,
    API_PROPERTY_INVALID_CLR_NAME,
    API_PROPERTY_INVALID_CLR_MEMBER,
    API_PROPERTY_INVALID_FIELD_GETTER,
    API_PROPERTY_INVALID_FIELD_SETTER,
    API_PROPERTY_INVALID_PROPERTY_GETTER,
    API_PROPERTY_INVALID_PROPERTY_SETTER,
    API_PROPERTY_MISSING_CLR_MEMBER,
    API_PROPERTY_NULL_TYPE,
    API_PROPERTY_UNRESOLVED_TYPE,
    #endregion

    #region ApiRelationship Initialization Codes
    API_RELATIONSHIP_INVALID_NAME,
    API_RELATIONSHIP_UNRESOLVED_PROPERTY,
    #endregion

    #region ApiSchema Initialization Codes
    API_SCHEMA_DUPLICATE_ENUM_TYPE_API_NAME,
    API_SCHEMA_DUPLICATE_ENUM_TYPE_CLR_TYPE,
    API_SCHEMA_DUPLICATE_NAMED_TYPE_API_NAME,
    API_SCHEMA_DUPLICATE_NAMED_TYPE_CLR_TYPE,
    API_SCHEMA_DUPLICATE_OBJECT_TYPE_API_NAME,
    API_SCHEMA_DUPLICATE_OBJECT_TYPE_CLR_TYPE,
    API_SCHEMA_DUPLICATE_SCALAR_TYPE_API_NAME,
    API_SCHEMA_DUPLICATE_SCALAR_TYPE_CLR_TYPE,
    API_SCHEMA_INVALID_NAME,
    #endregion
}
